#!/bin/bash

# The binary should be called switch_cgi and be
# placed in /var/www/<folder>/cgi-bin
# Permissions: -rwxr-xr-x

echo Content-type: text/plain
echo

#cd /path/to/switch-file

PARAMS=`echo $QUERY_STRING | cut -d\? -f 2`

CHAN=`echo $PARAMS | cut -d\& -f 1`
ACT=`echo $PARAMS | cut -d\& -f 2`
GROUP=`echo $PARAMS | cut -d\& -f 3`

echo $QUERY_STRING
echo $PARAMS
echo $CHAN
echo $ACT
echo $GROUP

if [ -n "$GROUP" ]; then
  ./nexa "$CHAN" "$ACT" "$GROUP"
else
  ./nexa "$CHAN" "$ACT"
fi
